export const MEALS = [
    {
        id: 1,
        image: "images/bunbohue.png",
        name: 'Bun Bo Hue',
        description: 'A traditional Vietnamese dish from the central region of Hue, Vietnam. The broth is an oxtail-based mixture infused with tomatoes and spices, and served with vermicelli noodles and fresh greens.',
        featured: false,
        difficulty: 'world-class',
        mealtime: 'dinner',
        
    },
    {
        id: 2,
        image: "images/ramen2.png",
        name: 'Tonkatsu Ramen',
        description: 'A pork-based Japanese ramen dish served with traditional ramen noodles, chasu (roasted pork tenderloin), and fresh vegetables.',
        featured: false,
        difficulty: 'world-class',
        mealtime: 'dinner',
    },
    {
        id: 3,
        image: "images/ramen.png",
        name: 'Red Tonkatsu Ramen',
        description: 'Similar to the traditional white Tonkatsu Ramen, this red version offers a spicy addition to the broth. The addition of chili oil and Japanese peppers adds that extra kick.',
        featured: false,
        difficulty: 'mediocre',
        mealtime: 'dinner',
    },
    {
        id: 4,
        image: "images/angelwings.png",
        name: 'Angel Wings',
        description: 'A Laotian delicacy created by carefully extracting the meat and bones in a chicken wing and stuffing the insides with a mixture created from vermicelli noodles, chicken meat, other flavors.',
        featured: true,
        difficulty: 'world-class',
        mealtime: 'lunch',
    },
    {
        id: 6,
        image: "images/dimsum.png",
        name: 'Pork Dumplings (Shiu Mai)',
        description: 'A staple of Chinese dim sum, these delicious treats are created by wrapping a blend of pork, vegetables, and spices with a wonton wrapper and steamed to perfection.',
        featured: true,
        difficulty: 'world-class',
        mealtime: 'breakfast',
    },
    {
        id: 7,
        image: "images/appplatter.png",
        name: 'Korean App Platter',
        description: 'The perfect combination of korean fried options for those that are unsure of what they want. Deep-fried calamari and breaded chicken is combined with golden french fries and bacon-wrapped hotdogs',
        featured: false,
        difficulty: 'lousy',
        mealtime: 'breakfast',
    },
    {
        id: 8,
        image: "images/cheeseburgersalad.png",
        name: 'Cheese Burger Salad',
        description: 'Similar to the traditional white Tonkatsu Ramen, this red version offers a spicy addition to the broth. The addition of chili oil and Japanese peppers adds that extra kick',
        featured: false,
        difficulty: 'lousy',
        mealtime: 'lunch',
    },
    {
        id: 9,
        image: "images/hotpot.png",
        name: 'Sour Soup Hot Pot',
        description: 'Perfect for a chilly evening, Sour Soup Hot Pot is a combination of fresh vegetables, tofu, seafood, and different noodles cooked in a boiling hot pot (get it?) of Tom Yum sour broth.',
        featured: true,
        difficulty: 'lousy',
        mealtime: 'dinner',
    },
    {
        id: 10,
        image: "images/tacosalad.png",
        name: 'Taco Salad Bowl',
        description: 'If you want a quick and light lunch without sacrificing the flavors, the Taco Salad Bowl is the perfect choice. Filled with seasoned ground beef, lettuce, tomatoes, beans, sour cream and laden with hot sauce, the Taco Salad bowl will leave you begging for a second bowl!',
        featured: true,
        difficulty: 'mediocre',
        mealtime: 'lunch',
    },
    {
        id: 11,
        image: "images/kapoon.png",
        name: 'Kapoon',
        description: 'A traditional Mien dish that incorporates thick flour noodles in a flavorful broth. Topped with fresh herbs and bean sprouts, Kapoon is sure to fill your heart as well as your stomach.',
        featured: false,
        difficulty: 'mediocre',
        mealtime: 'dinner',
    },
    {
        id: 12,
        image: "images/kimchirice.png",
        name: 'Korean Kimchi Rise',
        description: 'A quick fix lunch that thinly-sliced beef marinated in a sweet, Korean BBQ sauce (Bulgolgi) served ontop of a bed of white rice and fresh, pickled kimchi.',
        featured: false,
        difficulty: 'lousy',
        mealtime: 'lunch',
    },
    {
        id: 13,
        image: "images/mangorice.png",
        name: 'Mango Rice Dessert',
        description: 'Fresh and tender mango served over sweet, glutonous coconut rice, adorned with sesame seeds. This unlikely combination is great mix of sweet and tangy!',
        featured: false,
        difficulty: 'mediocre',
        mealtime: 'breakfast',
    },

]